### ISSUE TITLE
face_normals all zero, ignoring! message and no visualization 

### ISSUE THREAD

**Issue by Danfoa** [mmatl/urdfpy#12]
Hi!

I was trying to visualize a [human hand](https://github.com/ubi-agni/human_hand) with which I am working with. 

I made the URDF and make the paths to the meshes relative as indicated. But when loading the model I am getting this messages for all the joints I believe:

```
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
```
And then when I try to visualize I get a crash error that tells me very little:

```
Traceback (most recent call last):
  File "urdfpy-test.py", line 23, in <module>
    u.show(cfg=cfg)
  File "/......//site-packages/urdfpy/urdf.py", line 3572, in show
    pyrender.Viewer(scene, use_raymond_lighting=True)
  File "/......//site-packages/pyrender/viewer.py", line 347, in __init__
    self._init_and_start_app()
  File "/......//site-packages/pyrender/viewer.py", line 997, in _init_and_start_app
    height=self._viewport_size[1])
  File "/......//site-packages/pyglet/window/xlib/__init__.py", line 173, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/......//site-packages/pyglet/window/__init__.py", line 606, in __init__
    context = config.create_context(gl.current_context)
  File "/......//site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
  File "/......//site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/......//site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context
```

I think the second part might have something to do with OpenGL, however can you explain to me the first messages please.

**Comment by Danfoa** [comment]
I will close this issue as I realize it is an OpenGL installation related error.

**Comment by zhuyifengzju** [comment]
> I will close this issue as I realize it is an OpenGL installation related error.

Hi,

   I am facing the same problem with visualization here. Would you be able to provide more information about what's the issue with OpenGL installation? Thanks!
