### ISSUE TITLE
networkx is out of date

### ISSUE THREAD

**Issue by walchko** [mmatl/urdfpy#4]
Can you update to the current library?

```
ERROR: urdfpy 0.0.18 has requirement networkx==2.2, but you'll have networkx 2.4 which is incompatible.
```

**Comment by sdahdah** [comment]
I am also having issues with NetworkX 2.2 on Python 3.9 and Python 3.10. I force-updated to NetworkX 2.6.3 and it's working fine so far

**Comment by yorickdewid** [comment]
Not sure it this is related, but networkx throws an error: `ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)`

**Comment by ZdenekM** [comment]
@yorickdewid These are my workarounds for Python 3.10.

```
import collections
import fractions
import math

fractions.gcd = math.gcd  # type: ignore

from collections.abc import Iterable, Mapping, Set  # noqa:E402

collections.Mapping = Mapping  # type: ignore
collections.Set = Set  # type: ignore
collections.Iterable = Iterable  # type: ignore

from urdfpy import URDF  # noqa
```

**Comment by littlebee** [comment]
> @yorickdewid These are my workarounds for Python 3.10.
> 
> ```
> import collections
> import fractions
> import math
> 
> fractions.gcd = math.gcd  # type: ignore
> 
> from collections.abc import Iterable, Mapping, Set  # noqa:E402
> 
> collections.Mapping = Mapping  # type: ignore
> collections.Set = Set  # type: ignore
> collections.Iterable = Iterable  # type: ignore
> 
> from urdfpy import URDF  # noqa
> ```

Tried the above changes and progressed to new error:
```
Traceback (most recent call last):
  File "/Users/bee/projects/strongarm/src/commons/urdf_utils.py", line 19, in <module>
    from urdfpy import URDF, Link, Joint, Mesh  # noqa:E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/strongarm/lib/python3.13/site-packages/urdfpy/__init__.py", line 1, in <module>
    from .urdf import (URDFType,
    ...<5 lines>...
                       Transmission, Joint, Link, URDF)
  File "/opt/anaconda3/envs/strongarm/lib/python3.13/site-packages/urdfpy/urdf.py", line 7, in <module>
    import networkx as nx
  File "/opt/anaconda3/envs/strongarm/lib/python3.13/site-packages/networkx/__init__.py", line 117, in <module>
    import networkx.readwrite
  File "/opt/anaconda3/envs/strongarm/lib/python3.13/site-packages/networkx/readwrite/__init__.py", line 15, in <module>
    from networkx.readwrite.graphml import *
  File "/opt/anaconda3/envs/strongarm/lib/python3.13/site-packages/networkx/readwrite/graphml.py", line 314, in <module>
    class GraphML(object):
    ...<52 lines>...
        }
  File "/opt/anaconda3/envs/strongarm/lib/python3.13/site-packages/networkx/readwrite/graphml.py", line 345, in GraphML
    (np.float16, "float"), (np.float_, "float"),
                            ^^^^^^^^^
  File "/opt/anaconda3/envs/strongarm/lib/python3.13/site-packages/numpy/__init__.py", line 400, in __getattr__
    raise AttributeError(
    ...<3 lines>...
    )
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.
```

**Comment by traversaro** [comment]
See also https://github.com/mmatl/urdfpy/issues/31 for a mantained version of urdfpy available on both PyPI and conda-forge.
